[package]
name = "sarkara"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
rabbit = "0.1"
blake2-rfc = "0.2"
argon2rs = "0.2"
memsec = "0.1"
ascon = "0.1"
norx-rust = { git = "https://github.com/sneves/norx-rust.git", optional = true }
newhope = { version = "0.1", default-features = false }

[dev-dependencies]
nix = "0.6"

[features]
norx = [ "norx-rust" ]
