[package]
name = "sarkara"
version = "0.6.2"
authors = ["quininer kel <quininer@live.com>"]
description = "A Post-Quantum cryptography library."
repository = "https://github.com/quininer/sarkara"
documentation = "https://docs.rs/sarkara/"
keywords = [ "post-quantum", "cryptography" ]
license = "MIT"

[dependencies]
seckey = "0.4"
rand = "0.3"
hc256 = "0.1"
blake2-rfc = "0.2"
argon2rs = "0.2"
ascon = "0.1"
newhope = { version = "0.1", default-features = false }
blissb = "0.2"
byteorder = "1.0"

[features]
default = [ "simd" ]
simd = [ "blake2-rfc/simd_asm", "argon2rs/simd" ]
