[package]
name = "sarkara"
version = "0.10.0-alpha"
authors = ["quininer kel <quininer@live.com>"]
description = "A experimental post-quantum cryptography library."
repository = "https://github.com/quininer/sarkara"
documentation = "https://docs.rs/sarkara/"
keywords = [ "post-quantum", "cryptography" ]
license = "MIT"
categories = [ "cryptography" ]

[badges]
travis-ci = { repository = "quininer/sarkara" }
appveyor = { repository = "quininer/sarkara" }

[dependencies]
rand = "*"
arrayref = "*"
seckey = "*"
kyber = { git = "https://github.com/quininer/kyber" }
dilithium = { git = "https://github.com/quininer/dilithium" }
