[package]
name = "sarkara"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
hc128 = "0.1"
blake2-rfc = "0.2"
argon2rs = "0.2"
memsec = "0.1"
ascon = { git = "https://github.com/quininer/ascon.git" }
norx-rust = { git = "https://github.com/sneves/norx-rust.git" }

[dev-dependencies]
nix = "0.6"
