[package]
name = "sarkara"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
libc = "0.2"
hc256 = "0.1"
blake2-rfc = "0.2"
argon2rs = "0.2"
memsec = "0.1"

[dev-dependencies]
nix = "0.6"
