[package]
name = "sarkara"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
seckey = "0.1"
rand = "0.3"
hc256 = "0.1"
blake2-rfc = "0.2"
argon2rs = "0.2"
ascon = "0.1"
newhope = { version = "0.1", default-features = false }
blissb = { git = "https://github.com/quininer/blissb.git" }

[features]
default = [ "simd" ]
simd = [ "blake2-rfc/simd_asm", "argon2rs/simd" ]
