[package]
name = "sarkara"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
rabbit = { version = "0.1", features = ["nostd"] }
blake2-rfc = { version = "0.2", features = ["simd"] }
argon2rs = { version = "0.2", features = ["simd"] }
memsec = "0.1"
ascon = "0.1"
newhope = { version = "0.1", default-features = false }

[dev-dependencies]
nix = "0.6"
